version: '3.5'

services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      kafka-cluster:
        ipv4_address: 192.168.33.5

  broker1:
    image: 'bitnami/kafka:latest'
    ports:
        - '9092:9092'
    environment:
      - KAFKA_CFG_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=192.168.33.5:2181
      - KAFKA_CFG_LISTENERS=PLAINTEXT://0.0.0.0:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://192.168.33.2:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_DELETE_TOPIC_ENABLE=true
    depends_on:
      - zookeeper
    networks:
      kafka-cluster:
        ipv4_address: 192.168.33.2

  broker2:
    image: 'bitnami/kafka:latest'
    ports:
      - '9093:9092'
    environment:
      - KAFKA_CFG_BROKER_ID=2
      - KAFKA_CFG_ZOOKEEPER_CONNECT=192.168.33.5:2181
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://192.168.33.3:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_DELETE_TOPIC_ENABLE=true
    depends_on:
      - zookeeper
    networks:
      kafka-cluster:
        ipv4_address: 192.168.33.3

  broker3:
    image: 'bitnami/kafka:latest'
    ports:
      - '9094:9092'
    environment:
      - KAFKA_CFG_BROKER_ID=3
      - KAFKA_CFG_ZOOKEEPER_CONNECT=192.168.33.5:2181
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://192.168.33.4:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_DELETE_TOPIC_ENABLE=true
    depends_on:
      - zookeeper
    networks:
      kafka-cluster:
        ipv4_address: 192.168.33.4


networks:
    kafka-cluster:
      ipam:
        driver: default
        config:
          - subnet: 192.168.33.0/24
